[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = "paris"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
