[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cross_chain_bridge = "5HVG1XFoN3KXa6gcFkCs7iFcHvtsbmY6drvP34S1mwn4"

[programs.localnet]
cross_chain_bridge = "5HVG1XFoN3KXa6gcFkCs7iFcHvtsbmY6drvP34S1mwn4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

# Wormhole Core Bridge (mainnet address, but cloned from devnet state)
[[test.validator.clone]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"

# Wormhole Core Bridge (devnet)
[[test.validator.clone]]
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"

# Token Bridge (devnet)
[[test.validator.clone]]
address = "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe"
