[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
cross_chain_bridge = "5HVG1XFoN3KXa6gcFkCs7iFcHvtsbmY6drvP34S1mwn4"
cross_chain_messenger = "6KCA7CLpqcAqgTNcwYCVKYRixvvRqcMMrAN7FAH1qJxW"

[programs.localnet]
cross_chain_bridge = "5HVG1XFoN3KXa6gcFkCs7iFcHvtsbmY6drvP34S1mwn4"
cross_chain_messenger = "6KCA7CLpqcAqgTNcwYCVKYRixvvRqcMMrAN7FAH1qJxW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# MPL Token Metadata (Metaplex)
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Wormhole Core Bridge (mainnet)
[[test.validator.clone]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"

# Token Bridge (mainnet)
[[test.validator.clone]]
address = "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb"
